# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7220c7cc3c5b4053a680b70d9f7e40c1fa89a1cd94a9dd502711a923ad2a285eba4f9b0c48b34af8c73d815b8b02b800e8d805fb658592885e29c71f9605558d

test:
  secret_key_base: 475da515a8d5d238c614fbb4f94d7149504ac9133a4543dd3a8f49ebcafbbe0d0f2aa7ed15a53212abdf7e8ca8ab72c3a6e488ba56aa1e46c356713af7fc3c4e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
